sudo: required
dist: dist
language: node_js
node_js:
  - "7"
install:
  - yarn
  - yarn add global bower
  - bower install
script: 
  - gulp build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  local_dir: dist
  on:
    branch: master